baseURL = 'https://FernandoVazquezJ.github.io/'
languageCode = 'es-mx'
title = 'Fernando Vazquez | Mecatrónica'
theme = 'PaperMod'

[params]
    homeInfoParams = { Title = "Hola, soy Fernando", Content = "Ingeniero Mecatrónico | Cinvestav | RAS IEEE" }
    