baseURL = 'https://fernandovazquezj.github.io/FernandoVazquezJ'
languageCode = 'es-mx'
title = 'Fernando Vázquez J | Ing- Mecatrónico'
theme = 'PaperMod'

[params]
    homeInfoParams = { Title = "Fernando Vázquez Jiménez", Content = "Ing. Mecatrónico | BUAP | CINVESTAV | RAS IEEE" }
    