baseURL = 'https://fernandovazquezj.github.io/'
languageCode = 'es-mx'
title = 'Fernando Vázquez J | Ing- Mecatrónico'
theme = 'PaperMod'

[params]

    [params.label]
        text = "Fernando Vázquez J"
        icon = "/images/logo-personal.png" # Un logo pequeño junto a tu nombre en el menú
        iconHeight = 35

    [params.homeInfoParams]
        Title = "Fernando Vázquez Jiménez"
        Content = "Ing. Mecatrónico | BUAP | CINVESTAV | RAS IEEE"

    # AQUÍ AGREGAS TU FOTO DE PERFIL
    [params.profileMode]
        enabled = true # Cambia a true si quieres una página de inicio tipo "tarjeta"
        title = "Fernando Vázquez Jiménez"
        subtitle = "Ingeniero Mecatrónico | BUAP | CINVESTAV | RAS IEEE"
        imageUrl = "/images/perfil.jpg" # Ruta a tu foto en static/images/
        imageWidth = 150
        imageHeight = 150
        imageDisplay = "rounded" # Para que sea circular
        [[params.profileMode.buttons]]
            name = "Sobre mí"
            url = "/about/"
        [[params.profileMode.buttons]]
            name = "Proyectos"
            url = "/projects/"

[[menu.main]]
    identifier = "projects"
    name = "Projectos"
    url = "/projects/"
    weight = 10

# Submenú: Investigación (Research)
[[menu.main]]
    identifier = "research"
    name = "Investigación"
    parent = "projects" # Esto lo vincula al de arriba
    url = "/projects/research/"
    weight = 1

# Submenú: Impresión 3D
[[menu.main]]
    identifier = "3dprinter"
    name = "Impresión 3D"
    parent = "projects"
    url = "/projects/3d-printer/"
    weight = 2
#
# Submenú: Otros Proyectos
#[[menu.main]]
#    identifier = "mis-proyectos"
#    name = "Mis Desarrollos"
#    parent = "projects"
#    url = "/projects/otros/"
#    weight = 3